### ISSUE TITLE
Increase Unit Test coverage for CardContentAdapter.kt

### ISSUE THREAD

**Issue by katielevy1** [intuit/truffle-shuffle#25]
![image](https://user-images.githubusercontent.com/8975181/94825084-be435a80-03d3-11eb-8e18-150cbc1883a2.png)
Increase unit test coverage for CardContentAdapter.kt by adding unit tests to CardContentAdapterTest.kt

**Comment by hwangange** [comment]
Interested in this issue!

**Comment by cfsnsalazar** [comment]
Just opened a PR that would fix this issue
