### ISSUE TITLE
Change test framework to MockK

### ISSUE THREAD

**Issue by katielevy1** [intuit/truffle-shuffle#31]
Add in MockK dependency
Change ALL unit tests to use MockK
https://mockk.io/

**Comment by henry398** [comment]
Hello! I'd like work on this if possible.

**Comment by cfsnsalazar** [comment]
Hello there!

Has this been completed yet? It would be nice to write some tests to understand the library more in depth

**Comment by katielevy1** [comment]
@cfsnsalazar sorry, this issue is already done. If you see any improvements to the tests using features of Mockk, feel free to contribute!

**Comment by cfsnsalazar** [comment]
@katielevy1 Cool. I imagined this was the case since there is a PR open addressing this ticket . Are we able to write tests using Mockk now ? Or any contributions would have to wait until the PR is merged ?

**Comment by katielevy1** [comment]
I just merged the PR so you should be good if you pull the latest

**Comment by cfsnsalazar** [comment]
@katielevy1  Perfect! Thanks
