### ISSUE TITLE
Upgrade Target SDK to 31

### ISSUE THREAD

**Issue by katielevy1** [intuit/truffle-shuffle#35]
To stay up to date with new Android versions, update target and compile Android SDK version from 30 to 31 in the build.gradle files. Run the application and tests to verify everything is working properly.

**Comment by sanchi0204** [comment]
Can I work on this? I am a participant at OSD.

**Comment by adrishyantee** [comment]
I want to take up this issue. Can I work on it?

**Comment by katielevy1** [comment]
@sanchi0204 got first dibs! Also, join the #truffleshuffle-2021 slack channel for OSD if you haven't already
