### ISSUE TITLE
Upgrade Kotlin version to 1.5.21

### ISSUE THREAD

**Issue by katielevy1** [intuit/truffle-shuffle#36]
Upgrade the Kotlin version defined in the build.gradle file from 1.4.10 to 1.5.21 and ensure it is compatible with the gradle version. Run the application to ensure everything works properly. Check release details to ensure nothing will break (non backwards compatible changes) https://kotlinlang.org/docs/releases.html#release-details

**Comment by adrishyantee** [comment]
Will you assign this issue to me? I am an OSD participant

**Comment by katielevy1** [comment]
@adrishyantee it is all yours! Also, join the #truffleshuffle-2021 slack channel for OSD if you haven't already
