### ISSUE TITLE
Integrate KT Lint

### ISSUE THREAD

**Issue by katielevy1** [intuit/truffle-shuffle#4]
Add in KT Lint for prettier code formatting for Kotlin: https://github.com/pinterest/ktlint

**Comment by cfsnsalazar** [comment]
I am super interested in working on this.

**Comment by cfsnsalazar** [comment]
When can I start?

**Comment by katielevy1** [comment]
@cfsnsalazar awesome, you can start whenever you have time! Create a branch off the repo, add the library in, and then reformat the code

**Comment by nsalazar1992** [comment]
Awesome

**Comment by cfsnsalazar** [comment]
@katielevy1 I believe I do not have access to create a branch in this repo directly. I have forked it and started working. Should I be able to ?

**Comment by katielevy1** [comment]
You're correct, you should create a fork of the repo and then you can create a PR onto this repo from your fork (https://help.github.com/en/articles/creating-a-pull-request-from-a-fork). The master branch is the "develop" branch

**Comment by cfsnsalazar** [comment]
@katielevy1  I have closed my previous pr and opened the latest one after implementing ktlint in another project and learning a bit more about the library. The project should just check and reformat using Gradle tasks as expected. However, I would recommend using ktlint pre-commit hook to avoid committing unformatted code

**Comment by VMadalin** [comment]
@cfsnsalazar Absolutely agree with you to configure an `pre-commit` hook on the project, not only with the ktlint adding also different static analysis tools for copyright and etc.. 

IMHO it also necessary to add it on `CI Travis` task, for guaranty all PR are passed the checks before `merge`, avoiding to merge commits with `bypass commit hooks` option

**Comment by cfsnsalazar** [comment]
@VMadalin I agree with you 100%. In fact, I just updated my pr so that `./gradlew ktlint` runs every time someone commits. If the format is not right, the build is supposed to fail (I tested it in this commit [)](https://github.com/intuit/truffle-shuffle/pull/7/commits/69c66e475191164a47a3b3bec23bfd716c9bbb90).

**Comment by juliabirkett** [comment]
@cfsnsalazar are you working on this or can I get it?

**Comment by cfsnsalazar** [comment]
@juliabirkett yes. I have finished it. Here is the pr --> [https://github.com/intuit/truffle-shuffle/pull/7](url)

I am waiting for @katielevy1 to get back to me

**Comment by umartinez22** [comment]
Excellent.

**Comment by navasmdc** [comment]
Hey guys! I would like to contribute with this project 😉 
How can help you?

**Comment by katielevy1** [comment]
@navasmdc look at some of the other issues for the repo and pick one you would like to work on!

**Comment by katielevy1** [comment]
@cfsnsalazar thanks for contributing!
