### ISSUE TITLE
Accessibility: update onclick listener lambda to call view.performClick

### ISSUE THREAD

**Issue by katielevy1** [intuit/truffle-shuffle#47]
Inside the CardContentAdapter, update the setOnTouchListener to call view.performClick when there is a click.
Update the following lambda function:
```cardView.setOnTouchListener(View.OnTouchListener { view, event ->
                return@OnTouchListener when (event.actionMasked) {
                    MotionEvent.ACTION_DOWN -> true
                    MotionEvent.ACTION_UP -> {
                        cardViewGroup.click(view.tag as Int)
                        true
                    }
                    else -> false
                }
            })
```
Read more: https://stackoverflow.com/questions/24952312/ontouchlistener-warning-ontouch-should-call-viewperformclick-when-a-click-is-d

**Comment by amypritc** [comment]
Hi @katielevy1,  am a GHC attendee. Can I please work on this?

**Comment by katielevy1** [comment]
> Hi @katielevy1, am a GHC attendee. Can I please work on this?

Yeah!
